### ISSUE TITLE
No Duplicates in getValues();

### ISSUE THREAD

**Issue by gregoryyoung2** [gregoryyoung2/CSE231Winter2016-GroupProject-Team5#10]
I don't know if this is a problem for you guys but we need to make sure that we don't return any duplicates to Team 1 for one reason or another in our `getValues()` methods. It shouldn't be too difficult to make a method to make sure no duplicates are returned if they are currently being returned in the methods we have. 

Also apparently we need to make sure the first two sets of values are within the bounds 20 to 20,000 and the third array needs to be 20 to 30,000. I don't think this will be an issue but I wanted to let you guys know. 

This applies to @jardean05 @jeremyxy @ajstepp @willsonnate

**Comment by willsonnate** [comment]
@gregoryyoung2 I think the arrays that they will be passing to the queue will satisfy those conditions thus  we shouldn't need to do anything.

**Comment by gregoryyoung2** [comment]
@willsonnate Okay thats what I thought, just wanted to check with you guys.
