### ISSUE TITLE
Add third class

### ISSUE THREAD

**Issue by willsonnate** [gregoryyoung2/CSE231Winter2016-GroupProject-Team5#11]
Should we be adding a third class (Team05) that contains the two methods that team one requires? That way they're just creating a Team05 object then calling methods from there? The Team05 class would create two queues using our two queue classes and they would just be calling `team05.getTime()` and `team05.getValues()`.

@jeremyxy @jardean05 @ajstepp @gregoryyoung2

**Comment by ajstepp** [comment]
@willsonnate i think that is a great idea

**Comment by gregoryyoung2** [comment]
What would the goal of this be? From what I understand, what we would be doing is just creating another class that has two methods that just pull data from pretty much identically purposed methods in another class. I think if we document our two classes that we have well it will prevent confusion, as adding a third method could further complicate things and just add something else for team 1 to compile.

I guess what I'm saying is if we already have a `getValues()` and `getTime()` method in the two classes, what would we achieve by adding another class with identical methods just reiterates the information from these two methods.

**Comment by ajstepp** [comment]
once he's done lecturing we can discuss pros/cons

**Comment by gregoryyoung2** [comment]
@ajstepp Sounds good!

**Comment by gregoryyoung2** [comment]
Discussed in class
