### ISSUE TITLE
JUnit Test Not Completing

### ISSUE THREAD

**Issue by gregoryyoung2** [gregoryyoung2/CSE231Winter2016-GroupProject-Team5#20]
Hey Guys,

So I went through and worked on a JUnit test class. What I have going is a method that generates a random array of integers given an array size and minimum and max values. I've been using a size of 20,000 and a min and max of 1 and 100 respectively, in order to be as similar to what Team 1 will use as possible. Then I have a method that just takes in an int and returns `true` if odd and `false` if even. I use this method when I use my find odds method which does the following: first checks if there are at least 7,000 elements in the array (if not it just returns `{-1, -1}`), next searches the array starting at index 700 and find the first two odds and finally returns them as `{odd1, odd2}`. In the unlikely chance that there is less than two odds throughout the entire 700-7000 it will return -1. This all works as far as I can tell. 

My issue is that whenever I try to use @jardean05 and @jeremyxy's class I get `{-1, -1}` as the result of `getValues()` every time. All I am doing is passing through the int array I made in the constructor and then calling `getValues()` which is what team 1 should be doing. You may need to go through what you have to check that it works in an abstract context and not just through the main method.

I also ran into issues using @ajstepp and @willsonnate's class. The JUnit test stalls after running the constructor, I'm guessing this could be some kind of infinite loop in your for loop in the constructor but this  could be wrong. You might want to look at this also. I did the same exact implementation as with the previous class but just swapped in your method.

Obviously, there could be an issue with my logic so it would probably be a good idea to check over my code first. I tried to document it as well as possible but if you have any issues understanding something I did let me know. 

The JUnit test class is located over in [improvement/testClass](https://github.com/gregoryyoung2/CSE231Winter2016-GroupProject-Team5/tree/improvement/testClass). I'm going to throw some photos of what I'm getting at the end of this issue. I hope for at least one person in each partnership to try to run this code and look over your specific class.

Thanks,
Greg

<img width="566" alt="cl i o" src="https://cloud.githubusercontent.com/assets/8371627/14401375/1956e91a-fdde-11e5-8c7b-dbe71a331be3.png">

The following is using the Team05Queue.java class. Using QueueMonograph.java just stalled at the constructor so there was nothing to show for JUnit. 

<img width="693" alt="junit when comparing arrays as string" src="https://cloud.githubusercontent.com/assets/8371627/14401377/1f3f754a-fdde-11e5-82a6-418a85ab799c.png">

<img width="771" alt="junit when comparing arrays" src="https://cloud.githubusercontent.com/assets/8371627/14401378/2320a328-fdde-11e5-85ae-4b503d9732a0.png">

**Comment by ajstepp** [comment]
hey greg, im looking at the test and i dont see anything that actually calls the constructor for mine and @willsonnate class (QueueMonograph). also im curious as to why you're checking the length of the array to see if its over 7000? i was under the impression that we were searching for odd integers of value between 700 and 7000, not at array locations of 700 - 7000.

**Comment by willsonnate** [comment]
@gregoryyoung2 @ajstepp I just checked and we do have a infinite loop in our getValues() method. If there are no odd values between 700 and 7000 the loop doesn't end. I'll fix that in our branch right now.

**Comment by ajstepp** [comment]
@gregoryyoung2 @willsonnate ive gone through the monograph for the class project a couple times and im not sure if he wants the first odd #'s between 700 and 7000 or if we're searching for the first 2 odd values between array[700] and array[7000]. im gonna write a getValues() that finds the first 2 negatives within array[700] and array[7000] just in case

**Comment by gregoryyoung2** [comment]
@ajstepp Sorry I wasn't clear enough but I just swapped out your class with the other class for the `tst` variable. And what you said makes more sense, I probably just read it wrong. I'm going to look into it a little bit more.

**Comment by gregoryyoung2** [comment]
@ajstepp Yeah just looked it over, you were definitely right with your first comment. I'm going to update my code.

>Team 5 will search the contents of each Queue for the **first 2 odd integers between 700 and 7,000** and record the efficiency results from Big O Notation using elapsed time.

**Comment by gregoryyoung2** [comment]
Resolved with https://github.com/gregoryyoung2/CSE231Winter2016-GroupProject-Team5/commit/43efb111218fa86d483af655fea26a7f4264ac9e

**Comment by gregoryyoung2** [comment]
@jardean05 @jeremyxy Don't worry about this, it was my mistake. Sorry to bother.
