### ISSUE TITLE
Infinite loop in QueueMonograph.java constructor

### ISSUE THREAD

**Issue by gregoryyoung2** [gregoryyoung2/CSE231Winter2016-GroupProject-Team5#22]
@willsonnate I believe you said you already fixed this in another thread. We can close this issue once you push to your branch and we merge to master.

**Comment by willsonnate** [comment]
@gregoryyoung2 I didn't find an infinite loop issue in the constructor only the getValues() method. I fixed the loop in getValues() though. Its pushed to the branch, i'll make a pull request.

**Comment by gregoryyoung2** [comment]
@willsonnate Ok, my mistake.

**Comment by ajstepp** [comment]
my bad, think i accidentally edited the master instead of the branch to fix this exact issue

**Comment by gregoryyoung2** [comment]
@ajstepp Yeah I saw that. It's no problem!
